import { PrismaClient } from '@prisma/client'
export default async function etudiantsMinistereSeeder(prisma: PrismaClient) {
  await prisma.etudiantMinistere.createMany({
    data: [
      {
        nom: 'Hanafi',
        prenom: 'Meriem',
        email: 'hanafi.meriem@email.com',
        matricule: '222231354808',
        dateNaissance: new Date('2004-11-17'),
        lieuNaissance: 'Kouba',
      },
      {
        nom: 'Behidj',
        prenom: 'Neila',
        email: 'behidj.neila@email.com',
        matricule: '222231640005',
        dateNaissance: new Date('2005-04-18'),
        lieuNaissance: 'Reghaia',
      },
      {
        nom: 'Ngono',
        prenom: 'Paul',
        email: 'paul.ngono@email.com',
        matricule: 'MAT20230003',
        dateNaissance: new Date('2001-03-30'),
        lieuNaissance: 'Garoua',
      },
      {
        nom: 'Kamga',
        prenom: 'Alice',
        email: 'alice.kamga@email.com',
        matricule: 'MAT20230004',
        dateNaissance: new Date('2000-08-17'),
        lieuNaissance: 'Bafoussam',
      },
      {
        nom: 'Mbappe',
        prenom: 'Kylian',
        email: 'kylian.mbappe@email.com',
        matricule: 'MAT20230005',
        dateNaissance: new Date('1998-12-20'),
        lieuNaissance: 'Paris',
      },
      {
        nom: 'Sow',
        prenom: 'Abdou',
        email: 'abdou.sow@email.com',
        matricule: 'MAT20230006',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Dakar',
      },
      {
        nom: 'Ndiaye',
        prenom: 'Sana',
        email: 'sana.ndiaye@email.com',
        matricule: 'MAT20230007',
        dateNaissance: new Date('2002-06-25'),
        lieuNaissance: 'Dakar',
      },
      {
        nom: 'Zahra',
        prenom: 'Yasmina',
        email: 'yasmina.zahra@email.com',
        matricule: 'MAT20230008',
        dateNaissance: new Date('2001-12-14'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Diop',
        prenom: 'Mamadou',
        email: 'mamadou.diop@email.com',
        matricule: 'MAT20230009',
        dateNaissance: new Date('2000-11-02'),
        lieuNaissance: 'Dakar',
      },
      {
        nom: 'Bamba',
        prenom: 'Ousmane',
        email: 'ousmane.bamba@email.com',
        matricule: 'MAT20230010',
        dateNaissance: new Date('2002-02-19'),
        lieuNaissance: 'Abidjan',
      },
      {
        nom: 'Toure',
        prenom: 'Aissatou',
        email: 'aissatou.toure@email.com',
        matricule: 'MAT20230011',
        dateNaissance: new Date('2003-03-23'),
        lieuNaissance: 'Conakry',
      },
      // Étudiants ajoutés à partir du CSV
      {
        nom: 'Aktoùche',
        prenom: 'Anis',
        email: 'anis.aktouche@email.com',
        matricule: 'MAT20230008',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Cherif',
        prenom: 'Manel',
        email: 'manel.cherif@email.com',
        matricule: 'MAT20230013',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Larbi',
        prenom: 'Oussama',
        email: 'oussama.larbi@email.com',
        matricule: 'MAT20230014',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Khalef',
        prenom: 'Douaa',
        email: 'douaa.khalef@email.com',
        matricule: 'MAT20230015',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Ghemati',
        prenom: 'Chaima',
        email: 'chaima.ghemati@email.com',
        matricule: 'MAT20230016',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Guéracḥa',
        prenom: 'Ramzi Wassim',
        email: 'ramzi.wassim.gueracha@email.com',
        matricule: 'MAT20230017',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Sayah',
        prenom: 'Khadidja',
        email: 'khadidja.sayah@email.com',
        matricule: 'MAT20230018',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Tedjini',
        prenom: 'Abd El Moncef',
        email: 'abd.el.moncef.tedjini@email.com',
        matricule: 'MAT20230019',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Massoum',
        prenom: 'Mahieddinemoncef',
        email: 'mahieddinemoncef.massoum@email.com',
        matricule: 'MAT20230020',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Hamiti',
        prenom: 'Mohamed Nadir',
        email: 'mohamed.nadir.hamiti@email.com',
        matricule: 'MAT20230021',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      },
      {
        nom: 'Dziri',
        prenom: 'Mohammed Idir',
        email: 'mohammed.idir.dziri@email.com',
        matricule: 'MAT20230022',
        dateNaissance: new Date('2003-05-10'),
        lieuNaissance: 'Alger',
      }
    ],
    skipDuplicates: true
  })
  console.log('✔ Etudiants ministere seeded')
}
